# Generated by Django 4.2 on 2024-08-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_panel', '0014_studentprofile_intersted_extracurci_certification_and_more'),
        ('student_panel', '0015_student_profile_rename_type'),
    ]

    operations = [
    ]
