# Generated by Django 4.2 on 2024-08-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiadmin', '0003_feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
